server:
  port: 8081

spring:
  datasource:
    driver-class-name : com.mysql.cj.jdbc.Driver
    #localhost:3306로 접속하고, 데이터베이스 example을 사용했을 때
    #RDS 사용시 ec2 호스트 주소랑 데이터베이스 바꿔야 함
    url : jdbc:mysql://capston.cpeq2ag2c7l3.ap-northeast-2.rds.amazonaws.com:3306/capston?&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username : root
    password : capstonmysql
  thymeleaf:
      cache: false
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
openweathermap:
  key: 66c66a7e08f0dc0df1a26f9af58bf39e
default:
  latitude: 37.5665
  longitude: 126.9780