server:
  port: 8081

spring:
  datasource:
    driver-class-name : com.mysql.cj.jdbc.Driver
    url : jdbc:mysql://localhost:3306/example?&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username : root
    password : root
  thymeleaf:
      cache: false
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
openweathermap:
  key: 66c66a7e08f0dc0df1a26f9af58bf39e
default:
  latitude: 37.5665
  longitude: 126.9780