name: Java CI with Gradle

on:
  push:
    branches: [ "hs" ]
  pull_request:
    branches: [ "hs" ]

jobs: #실행될 프로세스 내
  build:
    runs-on: ubuntu-latest #실행될 인스턴스 OS 와 버전
    steps:
    - uses: actions/checkout@v4 # 깃허브에서 제공하는 checkout 액션 사용
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
      
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@417ae3ccd767c252f5661f1ace9f835f9654f2b5 # v3.1.0
    # gradle wrapper 파일에 실행 권한 부여
    # gradle wrapper : Gradle 빌드를 실행할 수 있게 해주는 것
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    # Gradle 빌드 액션을 이용해서 프로젝트 빌
    - name: Build with Gradle Wrapper
      run: ./gradlew build
    
    # 원격 서버에 jar 파일 전송
    - name: Send file to the server
      uses: appleboy/scp-action@master
      with:
          host: ${{ secrets.HOST }} #ec2 인스턴스 ip
          username: ${{ secrets.USERNAME }} #ubuntu 아이디
          key: ${{ secrets.PEMKEY }}  #ec2 인스턴스 pem key
          port: ${{ secrets.SSH_PORT }}  #접속포트번호 (보통 22)
          source: "./build/libs/*.jar"
          target: download

    #원격 서버 배포 스크립트 실행
    - name: Deploy remote ssh commands using password
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }} #ec2 인스턴스 ip
        username: ${{ secrets.USERNAME }} #ubuntu 아이디
        port: ${{ secrets.SSH_PORT }} #접속포트번호 (보통 22)
        key: ${{ secrets.PEMKEY }} #ec2 인스턴스 pem key
        script_stop: true
        script: |
          sh deploy/deploy.sh
